### ISSUE TITLE
Latest pictures not showing

### ISSUE THREAD

**Issue by cplaetzinger** [scottsweb/wp-instagram-widget#101]
I use your widget on the front page of my wordpress blog. The front page is created/designed using elementor. Everything worked fine, but at some point the widget stopped showing the latest pictures. 

My site: https://www.adventure4five.de/
My instagram: https://www.instagram.com/adventure4five.de/

If there is anything I can try or debug please let me know

**Comment by scottsweb** [comment]
Hi
Images are cached for a few hours and will not be updated instantly on you site. If that is not the problem then please clear your transients with https://wordpress.org/plugins/artiss-transient-cleaner/

More info here: https://wordpress.org/support/topic/the-plugin-has-stopped-to-update-the-photos-2/

**Comment by cplaetzinger** [comment]
That has fixed the issue. Thanks for your fast reply!
