### ISSUE TITLE
The plugin is removed from WordPress.org

### ISSUE THREAD

**Issue by daviedR** [scottsweb/wp-instagram-widget#107]
Hi Scott,

Just figured out that the plugin is removed from WordPress.org repository. Do you have any idea what is the reason?

I have several themes integrated with your plugin and want to know if I can still use your plugin in my themes.

**Comment by scottsweb** [comment]
Please see this thread https://wordpress.org/support/topic/this-plugin-was-closed-on-january-30-2019-and-is-no-longer-available-for-downlo/
