### ISSUE TITLE
did not return 200 again

### ISSUE THREAD

**Issue by elbotho** [scottsweb/wp-instagram-widget#112]
I get the `Instagram did not return a 200` Error and the `$remote` returns with:

```
{
  ["code"]=> int(404)
  ["message"]=> string(9) "Not Found"
}
```

The `$url` works fine in the browser and the account-feed I try to show is public.

Any body else has this problem? Did instagram change something or am I doing something wrong?

**Comment by scottsweb** [comment]
Strange, if the page is not found it would imply that the username could not be found. Is the Instagram account set to be public? It needs to be for this plugin to work. Also possible that Instragram have changed something again.

**Comment by elbotho** [comment]
Account is public and I did check spelling. Let's see if s.o. else has this problem.
Thank you for your work!

**Comment by petethompson** [comment]
I'm having this issue too, on a client's site. Her feed is definitely public, and it was working via the plugin until we noticed, today, that it's returning "Instagram did not return a 200."

Any advice on troubleshooting this would be really helpful!

**Comment by feastdesignco** [comment]
Instagram has been returning 200 for over a day here as well.

**Comment by scottsweb** [comment]
I am also seeing issues, I think it is possible the shared hosting IP I am using has been blocked. I am testing some changes here: https://github.com/scottsweb/wp-instagram-widget/pull/117 if you want to give them a try

**Comment by petethompson** [comment]
I have a feeling this is something to do with a change in instagram's policy around their API. I tried using another method of displaying an instagram feed on the same client's website, using the same instagram feed, but authorizing via an API key, and it's not returning any errors.

**Comment by scottsweb** [comment]
This plugin does not use the official API which is why it can sometimes be a battle @petethompson - but generally the scraping approach this plugin uses is sound, providing it doesn't get blocked :)

**Comment by scottsweb** [comment]
If you test my branch in #117 you can use the filter `add_filter('wpiw_proxy', '__return_true');` to get around IP restrictions if you feel that is the cause of your breakage.

**Comment by scottsweb** [comment]
This project is being archived (background in #118). Instagram filed a trademark complaint which saw the plugin removed from WordPress.org and then proceeded to block it from accessing instagram.com. All issues are being closed and it will soon be in a read only state.
