### ISSUE TITLE
Return of - Instagram has returned invalid data.

### ISSUE THREAD

**Issue by chado99** [scottsweb/wp-instagram-widget#118]
Hello, In the last few weeks I've noticed this occurring on the site I manage "Instagram has returned invalid data."   It is using the Foodie Pro wordpress theme which relies on this plugin.  Ive been using version 2.0.3 and just deleted and redownloaded and installed. Still issues. I've also tried using a different (public) instagram handle, still has issues. I am using the @ (not hashtag).

**Comment by scottsweb** [comment]
See #112 or test https://github.com/scottsweb/wp-instagram-widget/pull/117

**Comment by chado99** [comment]
Thanks for the quick reply. I'd like to download/try your test of 2.0.4, but a bit newer to github. How do you recommend me downloading the .zip so I can upload via the WP Panel?  thanks in advance.

**Comment by scottsweb** [comment]
Yes, grab the zip from here: https://github.com/scottsweb/wp-instagram-widget/archive/fixes/two-point-oh-four.zip and upload manually, see how you get on.

**Comment by scottsweb** [comment]
Let me know how you get on too, so I can merge it if all is well.

**Comment by chado99** [comment]
Hey, there. Uploaded, configured and tried in incognito and still seems to be having an issue (see screenshot).   Let me know if there is anything you want me to try to trouble shoot.
![image](https://user-images.githubusercontent.com/17997784/63468039-0ef03200-c424-11e9-989c-3f9fe70b353a.png)

**Comment by vsdphotos** [comment]
I just uploaded 2.0.4 as well and am still getting the same error message.

**Comment by DavePodosyan** [comment]
I'm having the same issue as well.

**Comment by crueltyfreecrystal** [comment]
I'm having the same issue but am confused as to what to do about it in #117

**Comment by lagodbout** [comment]
I’m having the same problem as well ! Could you give us more précisions on what needs to be done in #117 ? Thanks!

**Comment by scottsweb** [comment]
For those unsure what to do:

1. Download this ZIP: https://github.com/scottsweb/wp-instagram-widget/archive/fixes/two-point-oh-four.zip
2. Upload it manually via the plugins screen in WordPress: https://docs.presscustomizr.com/article/318-how-to-upload-a-wordpress-plugin-from-your-wordpress-admin-dashboard
3. Let me know if it fixes anything for you

**Comment by safmedina** [comment]
Hi there. 
Unfortunately, the latest fix does not work.

**Comment by chameleo24** [comment]
Hi
No change after update ...

**Comment by volthemes** [comment]
not sure why, it works fine on localhost, but not on the live site

**Comment by scottsweb** [comment]
If you find it is working on a local envrionment, then it could be that Instagram has blocked IPs related to shared hosts. In the latest version `2.0.4` you can test a special filter `add_filter('wpiw_proxy', '__return_true');` to see if that does the trick.

**Comment by Qksi** [comment]
Still "Instagram returned invalid data" with v. 2.0.4
www.MaciejRafalski.pl

**Comment by lukestateson** [comment]
Tried wget the URL of Instagram profile from server and it redirects to login page.

**Comment by volthemes** [comment]
> 
> 
> If you find it is working on a local envrionment, then it could be that Instagram has blocked IPs related to shared hosts. In the latest version `2.0.4` you can test a special filter `add_filter('wpiw_proxy', '__return_true');` to see if that does the trick.
> 
> This risk then becomes that this method gets blocked too... but we shall see.

great. it works fine with the code.
thanks!

**Comment by lukestateson** [comment]
The proxy method works fine.

**Comment by onholidayblog** [comment]
Hi there. I am having the same issue. I added the new version. But where I am supposed to add the code you're talking about?

**Comment by lukestateson** [comment]
> Hi there. I am having the same issue. I added the new version. But where I am supposed to add the code you're talking about?

you can try adding this code inside functions.php in your theme

**Comment by yvonskaiky** [comment]
Hi, by adding add_filter('wpiw_proxy', '__return_true'); to the fuctions.php is working. thanks. just an rdm question is it possible to add connection via ID and token of a specific account of IG on a side? seams other plugins who offers this solution is been able to connect to a specific account ID with no problem. thanks

**Comment by lagodbout** [comment]
Hi - Will you be updating the plugin soon with the solution ? - or is it absolutely necessary to go add the the filter to the function.php or our site ? Thanks !

**Comment by scottsweb** [comment]
@yvonskaiky 

> is it possible to add connection via ID and token of a specific account of IG on a side?

There are many plugins that go the token route, this plugin was always an alternative to that. Easier to setup, less fuss. I wouldn't want to create an Instagram app and share the tokens on GitHub. Firstly that would require I create an Instagram/Facebook account and secondly it would be less than ideal to share those tokens publically. 

@lagodbout 

The plugin has been removed from WordPress.org so any upates are only going to be made available here, on GitHub. I am going to merge this latest set of changes now and from then on you can update it with https://github.com/afragen/github-updater. You will need the proxy code for it to work - I don't want this to be the default for everyone as this new method will just be blocked too.

**Comment by scottsweb** [comment]
Changes now merged into `master`. I am going to leave this open for a few days to help others that stumble on it.

**Comment by plugloi** [comment]
Thank you very much. I like it. Fast support.

**Comment by plugloi** [comment]
> Hi, by adding add_filter('wpiw_proxy', '__return_true'); to the fuctions.php is working. thanks. just an rdm question is it possible to add connection via ID and token of a specific account of IG on a side? seams other plugins who offers this solution is been able to connect to a specific account ID with no problem. thanks

> adding add_filter('wpiw_proxy', '__return_true'); to the fuctions.php  <- This is answer.

**Comment by plugloi** [comment]
> Hi, by adding add_filter('wpiw_proxy', '__return_true'); to the fuctions.php is working. thanks. just an rdm question is it possible to add connection via ID and token of a specific account of IG on a side? seams other plugins who offers this solution is been able to connect to a specific account ID with no problem. thanks

@yvonskaiky Thank you. 
I adding add_filter('wpiw_proxy', '__return_true'); to the fuctions.php <- This is answer.

**Comment by infiniteembers** [comment]
Hello, I am having this issue as well. I'm hoping we're getting an update soon since it's affected all these users?

**Comment by scottsweb** [comment]
@infiniteembers please read the thread above ^

**Comment by infiniteembers** [comment]
I'm afraid I don't really understand anything written above, I don't know anything about coding and got confused but am trying to fix this issue on my blog. Is this the only solution?

**Comment by scottsweb** [comment]
@infiniteembers this is the solution:

1. Download the plugin: https://github.com/scottsweb/wp-instagram-widget/archive/master.zip
2. Upload the plugin manually: https://docs.presscustomizr.com/article/318-how-to-upload-a-wordpress-plugin-from-your-wordpress-admin-dashboard
3. If it still does not work, add the following code `add_filter('wpiw_proxy', '__return_true');` to your site. Normally done in the `functions.php` file of your theme.

There will be no more automattic plugin updates as it has been removed from the .org repo #115

**Comment by myshella** [comment]
> @infiniteembers this is the solution:
> 
> 1. Download the plugin: https://github.com/scottsweb/wp-instagram-widget/archive/master.zip
> 2. Upload the plugin manually: https://docs.presscustomizr.com/article/318-how-to-upload-a-wordpress-plugin-from-your-wordpress-admin-dashboard
> 3. If it still does not work, add the following code `add_filter('wpiw_proxy', '__return_true');` to your site. Normally done in the `functions.php` file of your theme.
> 
> There will be no more automattic plugin updates as it has been removed from the .org repo #115

Thank you! The update works for me.

**Comment by infiniteembers** [comment]
Thank you @scottsweb, you're very helpful! Downloading and uploading the plugin did not work for me, and I am receiving this error message when adding code in functions.php file:
<img width="1365" alt="Screen Shot 2019-08-22 at 11 04 49 AM" src="https://user-images.githubusercontent.com/54413853/63538967-dc9b0f00-c4cd-11e9-9f24-a8a1f46814b1.png">

It might be this is an unrelated problem on my site, have you encountered this before?

**Comment by infiniteembers** [comment]
Thank you very much for your help @scottsweb! The plug in did not work but adding the code did for me. I appreciate it.

**Comment by scottsweb** [comment]
@infiniteembers it looks like it wasn't happy with the change, make sure it is placed inside any existing `<?php` `?>` tags. It might also be that your host does not allow editing via WordPress iteself, so you would need to use FTP/SFTP or try adding it with a plugin: https://en-gb.wordpress.org/plugins/code-snippets/

**Comment by DavePodosyan** [comment]
> I'm having the same issue as well.

The issue was resolved by itself! I didn't update to 2.0.4.

**Comment by chado99** [comment]
I’m using a genesis child theme. Anyone know code snippet can be added via genesis simple hooks and if so where? I fear this change feting overwritten in the functions.php file  when genesis theme gets updated. 

> add_filter('wpiw_proxy', '__return_true');

**Comment by myshella** [comment]
Plugin no longer works :( 

 "Unable to communicate with Instagram." or "Instagram has returned invalid data."

**Comment by RaspberryFlavouredWindows** [comment]
Hi there, I've followed all the instructions to the letter but I still have 'Instagram has returned invalid data'. I'm up for a national blog award that is being judged in a weeks time and am in full blown panic mode. My theme is hemlock and this is the only plugin that works with the theme. Also when I updated to the new version I now get an error message saying the plugin isn't installed even though it is.

**Comment by plugloi** [comment]
> > I'm having the same issue as well.
> 
> The issue was resolved by itself! I didn't update to 2.0.4.

@DavePodosyan  Wow, How to resolve it?

**Comment by Qksi** [comment]
It seems methtod with proxy is blocked as well...
"Unable to communicate with Instagram"

**Comment by scottsweb** [comment]
I am seeing the same issue. It looks like the proxy method was short lived. I think it might be time to call it a day.

**Comment by iangeek** [comment]
> I am seeing the same issue. It looks like the proxy method was short lived. I think it might be time to call it a day.

@scottsweb Inclined to think you might be right :-/  It's been an invaluable plugin for a long time (I've been a long-time supporter of it), but looks like you're swimming against an ever-stronger tide, particularly if FB are starting to get serious on locking things down.

Props for all you've done so far though *highfives

**Comment by asadkn** [comment]
Even the API (token method) is going to be sunset in early 2020 as per official API docs, but it will work for a while. And the replacement Facebook Graph API is only for insta _business accounts_ and too has a strict app approval.

So Facebook being dev-hostile as usual. They don't want people getting the Instagram data at all in the future it seems.

**Comment by mickaelmaury** [comment]
Same problem for a client website [http://centre-aqua-lys.com](http://centre-aqua-lys.com) with theme Jacqueline WordPress theme and wp-instagram-widget version 2.0.4.

**Comment by chado99** [comment]
Same here, I had it working with 2.0.4 and proxy php code last night. Not working any longer. @feastdesignco will you be identifying any other Instagram plugins to replicate this in the Foodie Pro theme?

**Comment by AlchemyUnited** [comment]
FYI - When I var_dump($insta_array['entry_data']) I get this:

array(1) { ["LoginAndSignupPage"]=> array(1) { [0]=> array(4) { ["captcha"]=> array(2) { ["enabled"]=> bool(false) ["key"]=> string(0) "" } ["gdpr_required"]=> bool(false) ["tos_version"]=> string(3) "row" ["username_hint"]=> string(0) "" } } } 

It was working a couple days ago. We're on GoDaddy hosting, specifically just staging ATM. Not sure if that's (GoDaddy) part of the problem pattern.

**Comment by AlchemyUnited** [comment]
@feastdesignco - Actually, scraping - which is what this plugin is doing - is typically a simple ToS violation.  This could have happened a long time ago. IG  finally enforcing this is likely more related to privacy, security, and the (growing) fear of foreign entities and govs harvesting / collecting personal data.

**Comment by AlchemyUnited** [comment]
Has anyone considered IFTTT as a way to get IG image URLs? I'm not sure what would be the best Then That action.

**Comment by lukestateson** [comment]
The only way to save this plugin is to make the scrapes once a day and keep the data in transient for 24 hours with backup transient for 1 year.

And there is absolutely no way to keep it working on hosting with shared IP address.

**Comment by TanyavonZ** [comment]
Hi same here, must have been for the past few days that my 2.0.3 widget says now 'Instagram has returned invalid data. and since yesterday the Follow Me! link seems broken, too. I'm not a programmer, so not sure what to do. Deactivate and reactivate? Is it a bug to fix, or is it something that Instagram has blocked the connection to?

**Comment by amc2002** [comment]
> I am seeing the same issue. It looks like the proxy method was short lived. I think it might be time to call it a day.

Thanks for keeping this awesome plugin going as long as you did. Cheers.

**Comment by HarmonieJ** [comment]
I'm having this same issue and have done the manual update and added the code and it's still not working. Is there anything else I can do to fix this?

**Comment by amc2002** [comment]
> I'm having this same issue and have done the manual update and added the code and it's still not working. Is there anything else I can do to fix this? I'm using the Zobo theme if that makes any difference

See posts above - FB/Instagram has basically chocked off all access and it looks like the dev, although trying to keep this plugin going for years on his own time, fighting FB/Instagram all the way, has finally run out of options to keep it going and said it's probably time to call it a day. The plugin has also been removed from the wordpress.org repository.  I'd probably move on to other options if you can.

**Comment by chado99** [comment]
Anyone here have recommendations for replacement plugins with similar functionality (but are working)?

**Comment by HarmonieJ** [comment]
> > I'm having this same issue and have done the manual update and added the code and it's still not working. Is there anything else I can do to fix this? I'm using the Zobo theme if that makes any difference
> 
> See posts above - FB/Instagram has basically choked off all access and it looks like the dev, although trying to keep this plugin going for years on his own time, fighting FB/Instagram all the way, has finally run out of options to keep it going and said it's probably time to call it a day. The plugin has also been removed from the wordpress.org repository. I'd probably move on to other options if you can.

Thanks. It's a shame cause I liked this plugin. Very easy to use!

@chado99 yeah I'm with you, any recommendations for replacements?

**Comment by TanyavonZ** [comment]
I don't understand why Fb/Instagram wouldn't want this, it drives more people over to their site rather than the other way round. So, does that mean it's best to deactivate and no longer use the Instagram widget/plug in? If this is really the end of it, that's so sad, because it was really so great and beautiful.

**Comment by lukestateson** [comment]
> I don't understand why Fb/Instagram wouldn't want this, it drives more people over to their site rather than the other way round. So, does that mean it's best to deactivate and no longer use the Instagram widget/plug in? If this is really the end of it, that's so sad, because it was really so great and beautiful. Thank you for that. :)

Yes. Or don't use shared IP hosting provider.

**Comment by WriteoftheMiddle** [comment]
Please help - I've tried everything above and still no luck.  I don't write or understand coding much.  Here's a screenshot of where I have added the code mentioned into my Functions php.  Have I put it in the right/wrong place?  Thanks for any assistance.
![Screen Shot 2019-08-26 at 9 41 38 am](https://user-images.githubusercontent.com/54515640/63657526-92c06a80-c7e6-11e9-84eb-8ca730ce9c3e.png)

**Comment by WriteoftheMiddle** [comment]
Oh - have just read the later comments.  Is there nothing to fix this?  Is this the end of this plugin?  Any recommendation of what else might work ?

**Comment by lukestateson** [comment]
> Oh - have just read the later comments. Is there nothing to fix this? Is this the end of this plugin? Any recommendation of what else might work ?

Switch from shared hosting.

**Comment by HarmonieJ** [comment]
> > Oh - have just read the later comments. Is there nothing to fix this? Is this the end of this plugin? Any recommendation of what else might work ?
> 
> Switch from shared hosting.

And if we don't want to do that? Any other plugins that would work?

**Comment by AlchemyUnited** [comment]
@lukestateson  - Moving from shared hosting might help, but for how long? I presume IG's ToS has "rules" against scraping, right? Don't get me wrong, we love this plugin but it's now difficult to predict what IG will do in the future.

**Comment by AlchemyUnited** [comment]
@scottsweb  - Hey Scott. I was thinking about this over the weekend and I see two possible solutions. 

1) Use IFTTT or Zapier to get the images from IG, tho' I'm not sure where to send them (Google Drive? OneDrive?) and how to get them from there, If there was a way to get them into an RSS feed that should be good enough. You'll lose the link back to the individual images but, at least in our case, we're mostly interested in displaying the feed. From the IG profile page ppl can sort it out from there.

2) Use the official IG iframe embed, put it on a "hidden" webpage somewhere, and then scrape THAT page. IG believes it's rendering it's iframe, we get to avoid all that payload load on every page. This is probably the better idea of the two. It doesn't allow for scraping by tag, but at least most people will be able to get their own IG images, I think.

**Comment by scottsweb** [comment]
@AlchemyUnited can you provide an example or link to the iFrame embed option. I haven't seen that and it might provide some opportunities.

**Comment by kgshv** [comment]
Just a thought. Maybe consider giving this a new life by creating a plugin settings page and asking users for their Instagram username / password or for an access token? This might provide further food for thought maybe:
https://github.com/postaddictme/instagram-php-scraper

**Comment by AlchemyUnited** [comment]
@scottsweb - Oh. I guess I was under the impress that IG has one in the same way FB, Tw, etc. have one. Maybe not? 

Maybe this could help?

https://www.developerdrive.com/how-to-embed-an-instagram-feed/

**Comment by AlchemyUnited** [comment]
@kgshv - Interesting. Nice find.

**Comment by HarmonieJ** [comment]
> @scottsweb - Oh. I guess I was under the impress that IG has one in the same way FB, Tw, etc. have one. Maybe not?
> 
> Maybe this could help?
> 
> https://www.developerdrive.com/how-to-embed-an-instagram-feed/

Thanks for the link. Just downloaded the smash balloon one and it's working now. Not as clean and nice as this plugin, but it's doing the job. Cheers

**Comment by iangeek** [comment]
> @HarmonieJ - So with that other one I presume you have to enter your IG credentials, yes? When you say "not as clean and nice" what do you mean? tia

@AlchemyUnited  With the Smash Balloon one, they've registered the plugin as a third-party app with IG, which you then authorize access for the plugin to access your account (https://www.instagram.com/oauth/authorize/?[yadda-yadda-whatevs] ).  So obviously not ideal, who knows what's going on with the data, etc etc. But it works, and is presumably within IG's TOC.  I've got one or two sites I've inherited along the way that use it.  Although even then its not perfect, with IG occasionally just dropping the authentication without warning or reason, causing you to re-authorize.

**Comment by vatologic** [comment]
The proxy fix is definitely dead as far as shared hosting is concerned. Just dug a little deeper and the raw HTTP that I'm getting from a local _command line > cURL_ or _php > file_get_contents();_ call is vastly different from the same call from my shared hosting. It seems Zuckerberg found a way to filter automated requests.

As far as I can discern, the official API /GraphQL isn't going to be of much help - as it's limited to the authorised account. One could theoretically build a local system that does the scraping, but once those requests get out of hand - or too regular; an IP ban is most likely eminent.

**Comment by mbast100** [comment]
how do you update a plugin through a URL like you mentioned in the README for version 2.0.4.

thanks !

**Comment by scottsweb** [comment]
@AlchemyUnited I haven't tested on a single image page, I am not aware of those pages containing the JSON object we need though... and scraping one page at a time is more likely to lead to a ban as suddenly we are hitting 12ish pages a time.

**Comment by scottsweb** [comment]
@mbast100 just upload the zip file manually is easiest. Details above in this comment: https://github.com/scottsweb/wp-instagram-widget/issues/118#issuecomment-524009143

**Comment by AlchemyUnited** [comment]
@scottsweb - Yeah. Agree. I'm just poking around for answers / possibilities. If you transient'ed the images it could cut down on scrapes. 

That said, we ended up using the Smash Balloon plugin as well. In fact, I whipped up a plugin so we would use it via widget as well.  I haven't really looked at the impact on page load 'cause this came up outta nowhere and I just needed to get something done and in place. The plugin works but the code (quality) wasn't great. 

@HarmonieJ  - you might be interested in this too

https://gitlab.com/WPezPlugins/wpez-instagram-feed-widget

**Comment by honlapdavid** [comment]
> @infiniteembers this is the solution:
> 
> 1. Download the plugin: https://github.com/scottsweb/wp-instagram-widget/archive/master.zip
> 2. Upload the plugin manually: https://docs.presscustomizr.com/article/318-how-to-upload-a-wordpress-plugin-from-your-wordpress-admin-dashboard
> 3. If it still does not work, add the following code `add_filter('wpiw_proxy', '__return_true');` to your site. Normally added in the `functions.php` file of your theme or via plugin, e.g: https://en-gb.wordpress.org/plugins/code-snippets/
> 
> There will be no more automattic plugin updates as it has been removed from the .org repo #115

I tried it this methode, but no working. Any other tips? Thank you.

**Comment by reb013** [comment]
@scottsweb Any ETA on this fix or is this or is it dead? I bought a theme that basically revolves around this plugin.  A non-coding fix- The hashtag option still works. If you create a hashtag that is completely unique to your instagram account and post it in your photo captions, then you can work around this.

**Comment by scottsweb** [comment]
@reb013 @honlapdavid I am not aware of any fix for this currently. Instagram are blocking request and it is now out of my hands.

If you have purchased a theme you will need to speak to the person you purchased it from. They probably should have not built a business on a plugin whilst providing no investment or development to a product they depend upon.

**Comment by staruc** [comment]
Thanks for all your work on this, Scott. I've been unable to resolve this or contribute help in my projects.

To others, if you're just looking to add in a few photos from an Instagram feed, Smash Balloon's free version of their plugin should be sufficient: https://wordpress.org/plugins/instagram-feed/

They provide options to remove all of the excess bells and whistles.

**Comment by airplanenoise** [comment]
end of an era, for sure. this was the easiest way to get this done. we have slowly been replacing this with https://lightwidget.com which allows you to do a responsive simple grid. You can pay a very small fee to remove the watermark/copyrighting. Well worth not worrying about Instagram changing policies and code bases overnight.

**Comment by wpaholic** [comment]
Guys, checkout this plugin called WP Instant Feeds, works perfectly!
https://wordpress.org/plugins/wp-my-instagram/

**Comment by daonham** [comment]
Today's proxy options work perfectly. Does anyone know why? Will it die in the future?

**Comment by paranormallife** [comment]
> Guys, checkout this plugin called WP Instant Feeds, works perfectly!
> https://wordpress.org/plugins/wp-my-instagram/

Sorry, no it doesn't. **wp-my-instagram** has the same problem with shared servers.

**Comment by scottsweb** [comment]
I'm closing this issue now and will be removing recommendations as there are none that I endorse. 

The repo will be put into archive mode in a few days.

**Comment by Jany-M** [comment]
> Yes, grab the zip from here: https://github.com/scottsweb/wp-instagram-widget/archive/fixes/two-point-oh-four.zip and upload manually, see how you get on.

Link doesn't work. It cuts the .zip away from url and returns `404: Not Found`.
