### ISSUE TITLE
Instagram has returned invalid data

### ISSUE THREAD

**Issue by ybhrc** [scottsweb/wp-instagram-widget#120]
Hello- I have the message "Instagram has returned invalid data" displaying on my website. I am not a coder so if you have a simple fix that a simple mind can understand that would be great. I did try to deactivate and reactivate the plugin.

I have version 2.0.3

Thank you

**Comment by scottsweb** [comment]
Duplicate of https://github.com/scottsweb/wp-instagram-widget/issues/120

**Comment by ybhrc** [comment]
When I click on #120 it doesn't take me anywhere

**Comment by scottsweb** [comment]
Apologies. Try: https://github.com/scottsweb/wp-instagram-widget/issues/118
