### ISSUE TITLE
Instagram has returned invalid data.

### ISSUE THREAD

**Issue by lyrathemes** [scottsweb/wp-instagram-widget#122]
Using version 2.0.4

`print_r($remote)` resulted in the following:

[remote.txt](https://github.com/scottsweb/wp-instagram-widget/files/3603800/remote.txt)

**Comment by goodwinpress** [comment]
Sorry, but same problem with version 2.0.4. wpiw_proxy doesn't help (

**Comment by scottsweb** [comment]
Please see https://github.com/scottsweb/wp-instagram-widget/issues/118

The plugin is no longer maintained.

**Comment by vchabal** [comment]
my workaround, I replaced plugin with custom html, short example:
```
<div id="instasidebar"></div>
<script>
var insta_username = 'username_goes_here'
jQuery.getJSON({
    url: 'https://www.instagram.com/'+insta_username+'/?__a=1',
    success: function(data) {
        var posts = data.graphql.user.edge_owner_to_timeline_media.edges.slice(0, 9), 
            html = [];
        for (var i = 0; i < posts.length; i++) {
            html.push('<a href="https://www.instagram.com/p/' + posts[i].node.shortcode + '"><img src="' + posts[i].node.thumbnail_src + '" width=33.33% /></a>')
        }
        document.getElementById('instasidebar').innerHTML = html.join('');
    }
});
</script>
```

**Comment by scottsweb** [comment]
I don't recommend the jQuery approach. Every page load will require a new request to Instagram which will be slow and increase your chances of getting blocked. Any request needs to be cached.
