### ISSUE TITLE
Allow usage of the remote request via a hook

### ISSUE THREAD

**Issue by Mr-Alexander** [scottsweb/wp-instagram-widget#123]
It would be great to have access to the remote response for further processing via ideally have a way to store it with the other data in the transient not just the images. For example to get the profile picture and use it in the output as well.

**Comment by scottsweb** [comment]
This project is being archived (background in #118). Instagram filed a trademark complaint which saw the plugin removed from WordPress.org and then proceeded to block it from accesing instagram.com. All issues are being closed and it will soon be in a read only state.
