### ISSUE TITLE
Widget stopped working in footer

### ISSUE THREAD

**Issue by artsycat** [scottsweb/wp-instagram-widget#124]
The Instagram feed stopped showing up in the footer of [this website ](https://laylatheblackcat.com)about a month ago. Attached is a screen a shot of the error I'm getting. The theme is Highend just FYI. 

<img width="1640" alt="Screen Shot 2019-09-17 at 1 41 25 PM" src="https://user-images.githubusercontent.com/15255226/65066114-c27c1180-d951-11e9-9a65-af45f446cc8a.png">

**Comment by scottsweb** [comment]
Please see #118 - the TLDR; is that this plugin has had to be discontinued due to Instagram blocking it and then filing a trademark complaint to the WordPress.org repo.
