### ISSUE TITLE
Output HTML prior to the images loop

### ISSUE THREAD

**Issue by Mr-Alexander** [scottsweb/wp-instagram-widget#125]
It would be neat to have an action hook to output HTML before the media loop,

before this:

```
<<< here >>>
	?><ul class="<?php echo esc_attr( $ulclass ); ?>"><?php
	foreach( $media_array as $item ) {
```

The issue with `do_action( 'wpiw_before_widget', $instance );` is that you don't know the username yet or have access to the media array.

**Comment by scottsweb** [comment]
This project is being archived (background in #118). Instagram filed a trademark complaint which saw the plugin removed from WordPress.org and then proceeded to block it from accesing instagram.com. All issues are being closed and it will soon be in a read only state.
