### ISSUE TITLE
instagram image not show in domain .com.co 

### ISSUE THREAD

**Issue by vannha** [scottsweb/wp-instagram-widget#126]
Hi,
am using this widget on my WP site:  https://pomboylola.com.co/?post_type=post
and now it not showing any image, just a message: Instagram has returned invalid data.

my Instagram:  https://www.instagram.com/pombo_lola/

here is my config for widget: http://prntscr.com/p81b3g

please help me!

**Comment by scottsweb** [comment]
Please see #118 - the TLDR; is that this plugin has had to be discontinued due to Instagram blocking it and then filing a trademark complaint to the WordPress.org repo.
