### ISSUE TITLE
Instructions to size the images?

### ISSUE THREAD

**Issue by danyork** [scottsweb/wp-instagram-widget#20]
Hi there. First, **thanks** for making this plugin!  A friend asked me about adding her Instagram feed to her WordPress site and I said "there had to be a plugin that did this"... and there was.  Before putting it on her site, though, I tried it on mine...    and it was fine.

But then this week I upgraded to version 1.5.1 (from 1.4) and suddenly my images are going off the side of my page ( you can see it on the right of http://danyork.me/ if you scroll down).  I see you removed the option to choose what size the images are.

Given that, what do I do to size the images?  Presumably I'm going to need to style the images in the CSS of my theme... could you please provide some instructions or examples? Perhaps in the FAQ?

Also - any chance you can bring back an option to size the images in the widget?   While I'm okay going in an mucking around with my CSS, I'm not sure all users of the widget will want to do so.

Thanks again for making this plugin/widget.

**Comment by scottsweb** [comment]
This widget uses an unofficial approach to obtaining images from the Instagram site. Last week Instagram made some changes that meant we had to quickly patch the plugin and as a result we also had to sacrifice some functionality. 

A full history of that can be found here: https://wordpress.org/support/topic/php-error-messages-in-place-of-widget?replies=40

I am going to leave this issue open as I may consider adding size selection back using a few custom CSS classes if more feedback if this type comes in.

**Comment by danyork** [comment]
Ah, I understand now.  Interesting that you are just scraping the site. Clever!  But then I understand why you don't have the size info.    I do see two more people in that wordpress.org thread asking if size selection can come back.

I think the challenge could be that everyone's layout is going to be different and so the choice of sizes is going to be challenging... with someone always wanting some other combination.  But an approach of offering a couple of different choices and then providing instructions on how to modify the CSS if you want a different size might work well.

Thanks again.

**Comment by scottsweb** [comment]
Further suggestions for image sizes here: https://wordpress.org/support/topic/option-to-scale?replies=1#post-7156841- recommended to use Photon which seems like a good approach.

**Comment by scottsweb** [comment]
Further image size discussion here: https://wordpress.org/support/topic/php-error-messages-in-place-of-widget/page/2?replies=46#post-7276836 - this seems like the best approach.

**Comment by danyork** [comment]
Fascinating. I just tried that with a couple of different sizes and it seemed to work fine. Very cool!
