### ISSUE TITLE
Facebook taking wrong image

### ISSUE THREAD

**Issue by RodneyOlsen** [scottsweb/wp-instagram-widget#22]
I love the wp-instagram-widget but I find that when I try to add a recent post to Facebook, it pulls my instagram images instead of the post image. I then have to deactivate the plugin, add my post to Facebook, then reactivate the plugin. Any thoughts?

**Comment by scottsweb** [comment]
I would say to you need to implement open graph data on your website to better instruct Facebook which image it should be grabbing.. or move the widget below the article or featured image in your page structure.

There are many open graph plugins including Jetpack and Yoast SEO.
