### ISSUE TITLE
Force Square Images

### ISSUE THREAD

**Issue by scottsweb** [scottsweb/wp-instagram-widget#23]
https://wordpress.org/support/topic/display_src-vs-thumbnail_src?replies=1

**Comment by KirillDiz** [comment]
Hello!
I also have a problem with the display of photos in the widget . In instagramme can now upload photos of any size and not only the square . You wrote that the plan to solve this problem. I understood correctly ? Please tell me it is already known when will update ?
Thank you for your widget!

**Comment by KirillDiz** [comment]
Thank you so much!!!

**Comment by scottsweb** [comment]
No problem. It will be on WordPress.org soon. Hoping today.
