### ISSUE TITLE
i need some help to put in other side, no in the sidebar

### ISSUE THREAD

**Issue by rubenmedios** [scottsweb/wp-instagram-widget#25]
I like to know if i can put any code to the end of content in my templates or at start of the footer.

any idea how i can do this?

**Comment by scottsweb** [comment]
I think you want this function: https://codex.wordpress.org/Function_Reference/the_widget

It allows you to output a widget anywhere within your theme templates. The other option is to register a custom sidebar:

https://codex.wordpress.org/Function_Reference/register_sidebar
https://codex.wordpress.org/Function_Reference/dynamic_sidebar
