### ISSUE TITLE
Add filter for Link Button

### ISSUE THREAD

**Issue by vburlak** [scottsweb/wp-instagram-widget#28]
@scottsweb thx for a great Instagram widget! It's really just fantastic easy to use.

i think it will be good to have ability to filter `<p class="clear">` that wrapping Follow Me link. 
Someone will want to add some classes or redeclare Follow Me link via `wpiw_after_widget` action with new markup(maybe `<button>` or something else). 
Without editing widget class this is not possible now.

```php
<?php if ( $link != '' ) {?>
     <p class="clear"><a href="//instagram.com/<?php echo esc_attr( trim( $username ) ); ?>" rel="me" target="<?php echo esc_attr( $target ); ?>"><?php echo $link; ?></a></p>
<?php } ?>
```

**Comment by scottsweb** [comment]
Will be available in the next release as a filter.

**Comment by vburlak** [comment]
@scottsweb oh, thanks a lot!
