### ISSUE TITLE
PageSpeed Insights

### ISSUE THREAD

**Issue by lewis-smith** [scottsweb/wp-instagram-widget#32]
When I run PageSpeed on my site I get:

`Compressing and resizing http://scontent.cdninstagram.com/…2301347_527182590776654_1950397863_n.jpg could save 94.8KiB (96% reduction).`

For all the Instagram images. I think this is mostly because they are being linked to at full size and then displayed at 83x83.

I guess the only way round this would be to cache the images on my server and then resize them to 83x83 there before displaying them.

I'm really tempted to do this because it seems to be having a bit impact on the speed score. Does this approach sound sensible to you? And is there anything I should be aware of before I jump into the code and attempt to make the change?

**Comment by scottsweb** [comment]
This is related to #29 - the format of the CDN URLs that Instagram use has changed recently. Previously [this code](https://github.com/scottsweb/wp-instagram-widget/blob/master/wp-instagram-widget.php#L197-L198) ensured that better images sizes were served based on the image size setting.

[This comment](https://wordpress.org/support/topic/some-images-use-thumbnails-other-use-larger-versions?replies=5#post-7590707) on .org suggests that size can still be added to a URL, I just haven't hide time to look at it. 

Appending a size to the URL this way will save the need to cache them locally. I would investigate that first.
