### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by P4KM4N** [scottsweb/wp-instagram-widget#36]
I did the update yesterday (v 1.9) and I got broken image, you can check it out in the footer: http://blog.myvirtualyoga.com/en/ 
![screen shot 2015-12-10 at 09 15 25](https://cloud.githubusercontent.com/assets/5093327/11717446/93ae50be-9f1e-11e5-8b4a-43d6ef48c697.png)

If I look up the image link, it say "Invalid Request".

**Comment by scottsweb** [comment]
#notetoself untrailingslashit - although it does not fully explain one all but one image are working
