### ISSUE TITLE
Error: undefined offset 4

### ISSUE THREAD

**Issue by daviedR** [scottsweb/wp-instagram-widget#37]
Hi Scotts,

Sometimes your plugin shows warning error:

Notice: Undefined offset: 4 in ......\wp-content\plugins\wp-instagram-widget\wp-instagram-widget.php on line 204

In one case, If the instagram feeds contains video, it shows the errors.

Could you check?

**Comment by scottsweb** [comment]
Can you provide your Instagram username so I can test your account. Thanks

**Comment by anhskohbo** [comment]
You can test with taylorswift :)
