### ISSUE TITLE
Use "template-parts" instead of "parts" for custom template

### ISSUE THREAD

**Issue by daviedR** [scottsweb/wp-instagram-widget#44]
Hi Scott,

I see you provide a way to use custom template for the instagram feed items, via `locate_template( 'parts/wp-instagram-widget.php' )`.

Can you also make it available for `template-parts` directory? I use [Underscores.me](http://underscores.me/) as a starting theme, and it declares `template-parts` directory as partial templates directory. I think you can also add `template-parts` directoy for the `locate-template` call, considering that Underscore.me is an official starting theme from Automattic.

Regards

**Comment by scottsweb** [comment]
A new pull request has introduced a filter for setting your own location for the template part: https://github.com/scottsweb/wp-instagram-widget/issues/43
