### ISSUE TITLE
Page Speed test

### ISSUE THREAD

**Issue by daviedR** [scottsweb/wp-instagram-widget#45]
Hi Scott,

I also run a test on GTmetrix and Pingdom. I noticed that your plugins miss some points:

* each image tag should have `width` and `height` attributes.
* each image tag should have `alt` attribute (from W3 validator)
* each image tag src has query parameter "ig_cache_key", is it important? because Page Speed hates query parameter on static files.

I think the `width`, `height`, and `alt` attributes are important to have.

Regards

**Comment by scottsweb** [comment]
This is an example image from the plugin:

```<img src="//scontent-lhr3-1.cdninstagram.com/t51.2885-15/e35/s160x160/12568914_875886349215670_64056159_n.jpg" alt="An update on our windowsill garden for today's #hdygg with @fableandfolk - link in bio.  #hyacinth #spring #indoorgarden #flowers #nature #colour" title="An update on our windowsill garden for today's #hdygg with @fableandfolk - link in bio.  #hyacinth #spring #indoorgarden #flowers #nature #colour" class="">```

The image URL does not contain any query strings and it does contain an `alt` tag. It sounds like you may have other plugins or services messing with your html. 

The `width` and height` are deliberately left off as we are not provided dimensions for the original image size from Instagram. It also makes it easier for people to work with the plugin. These can of course be set manually using your own template part.
