### ISSUE TITLE
Is 12 maximum number of images that could be fetched?

### ISSUE THREAD

**Issue by rahulnever2far** [scottsweb/wp-instagram-widget#47]
I'm trying to get 20 images as thumbnail using your plugin, but it doesn't fetch more than 12 images.

Could you please let me know if there is any way to change this limit?

**Comment by scottsweb** [comment]
The plugin scrapes JSON data from the Instagram website. The maximum number of images it can get is the number Instagram provide in the JSON data. If that is now 12 then unfortunately that is the limit.
