### ISSUE TITLE
Only 12 photos are displayed instead of 16

### ISSUE THREAD

**Issue by jennytai** [scottsweb/wp-instagram-widget#55]
This widget when applied to the footer of my blog only displayed 12 photos, even though I set it to 16. Four pictures are missing from the bottom row, two on each side.

**Comment by scottsweb** [comment]
Please see: https://github.com/scottsweb/wp-instagram-widget/issues/47

Instagram only allow me to scrape 12 images with a single request. There is a possibility we could make more requests, but I have not looked into it.
