### ISSUE TITLE
Images optimalisation

### ISSUE THREAD

**Issue by maciejstafiej** [scottsweb/wp-instagram-widget#58]
Hey, 
I am not sure  that I am writing in right place.

I have a really big problem with WP Instagram Widget at my Wordpress website. Google Page Insights shows error with the size of images. Test shows, that my page is 61/100 with, and 84/100 without your widget. Is it possible to put optimised pictures from Instagram on my site? I find it very useful, so I don't want to turn it off.

Best regards
Maciej Stafiej

**Comment by scottsweb** [comment]
Please see the discussion here: https://wordpress.org/support/topic/plugin-slows-down-website-on-google-speed-test/
