### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Bondra** [scottsweb/wp-instagram-widget#60]
I've run into some problem with your plugin. I get following error:
Fatal error: Call to undefined function wp_parse_url() in web\wp-content\plugins\wp-instagram-widget\wp-instagram-widget.php on line 212

Im running Wordpress 3.7 and WP Instagram Widget version 1.9.8

**Comment by scottsweb** [comment]
`wp_parse_url()` was introduced in WordPress 4.4. You need to update your WordPress installation in order to use this plugin.
