### ISSUE TITLE
Page Speed Test

### ISSUE THREAD

**Issue by jgajera** [scottsweb/wp-instagram-widget#62]
I know you closed out some PageSpeed issues in the past, but it seems GTMetrix is picking up this widget for scaling images improperly again. Removing the widget from the page makes the PageSpeed score jump 30-40%.

> http://scontent.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/c341.0.1365.1365/15338485_1630948793873116_6962549806845657088_n.jpg?ig_cache_key=MTM5OTYzNjA4MjMyOTkwOTM2Nw%3D%3D.2.c is resized in HTML or CSS from 640x640 to 128x128. Serving a scaled image could save 134.6KiB (96% reduction).

**Comment by scottsweb** [comment]
This is not a bug with the widget. Instagram provide just a few image sizes, make sure you choose the best one for your theme in the widget settings. 

Right now you have chosen then 640 size and your theme is then scaling that to 128 - if you want to get rid of the error, don't scale images with CSS.
