### ISSUE TITLE
Retrieve multiple media pages via method call

### ISSUE THREAD

**Issue by ilya-konanykhin** [scottsweb/wp-instagram-widget#63]
I'm using this plugin with a highly customized frontend, that is, only call `scrape_instagram` method and then do filtering/decoration/JS stuff.

The method strongly lacks ability to fetch media items from pages other than first — 2nd, 3rd and so on.

Adding this ability will also open a way to fetch more pics in the template, if the `number` option value is greater than 12.

**Comment by scottsweb** [comment]
This project is being archived (background in #118). Instagram filed a trademark complaint which saw the plugin removed from WordPress.org and then proceeded to block it from accessing instagram.com. All issues are being closed and it will soon be in a read only state.
