### ISSUE TITLE
New Instagram pics are not shown 

### ISSUE THREAD

**Issue by funkartist** [scottsweb/wp-instagram-widget#66]
Hi Scott,

I just discovered your Widget and I was using it for a few weeks but actually I noticed that the new pics I posted in the last days on Instagram are not being shown on my wordpress website anymore. I uninstalled and reinstalled the widget but it didn't work...it's still showing the older pics. Can you please help me out?

Thanks!

**Comment by scottsweb** [comment]
Give this a try: https://wordpress.org/support/topic/latest-images-not-pulling-through/#post-7147367

**Comment by funkartist** [comment]
THank you so much! Now it works! :)
