### ISSUE TITLE
"Instagram did not return any images."

### ISSUE THREAD

**Issue by naomimaria** [scottsweb/wp-instagram-widget#68]
Hello! I'm putting a site together and the plugin doesn't seem to be working. Unlikely a plugin conflict because I have deactivated all other plugins as a test and it's still not pulling from Instagram. 

This is the site – http://www.briemarieg.com/
This is the theme (not sure if helpful) – http://natalie.az-theme.net/

Thanks!

**Comment by scottsweb** [comment]
This normally 1 of 2 things:

1. Your instagram account is private. The plugin requires your profile to be public.
2. Your website host is blocking outbound requests. You would normally have a control panel (cpanel or similar) with settings for allowing outbound requests. If not contact your host and check with them.

**Comment by naomimaria** [comment]
Ahhhh, the account was private. Awesome, thank you for the help!
