### ISSUE TITLE
301 redirects

### ISSUE THREAD

**Issue by RojaBella** [scottsweb/wp-instagram-widget#69]
Hi, 

Reports from Screaming Frog identify the widget as throwing 301's for every instagram post that posts through the widget. Thoughts?  These are our settings. 

![image](https://user-images.githubusercontent.com/31214779/29525006-5b4cb1c8-865f-11e7-829f-b4c1a5d46abc.png)

![image](https://user-images.githubusercontent.com/31214779/29525113-aa1ade6a-865f-11e7-92b8-ada3861a6bef.png)

**Comment by scottsweb** [comment]
I will need some more information. Are the 301s on the front end of the site? Is the site publicly accessible? What does your report look like? Why is it a problem? 

Screaming Frog looks to be commercial software so I have no context.

**Comment by RojaBella** [comment]
I’ve asked my SEO guy to send me the full report from Screaming Frog and I’ll forward those details as soon as I get them. Thanks for the quick reply! 

 

Robin Jaffin, Co Founder

Business and Content Development

 

Pre-order  <https://www.amazon.com/Low-FODMAP-Diet-Step-Personalized-Disorders/dp/0738219347/ref=s9u_simh_gw_i1?_encoding=UTF8&fpl=fresh&pf_rd_m=ATVPDKIKX0DER&pf_rd_s=&pf_rd_r=XNW2R555VGWFTKRYT5GD&pf_rd_t=36701&pf_rd_p=a6aaf593-1ba4-4f4e-bdcc-0febe090b8ed&pf_rd_i=desktop> The Low-FODMAP Diet Step by Step

Stay Tuned for the Launch of FODMAPeveryday.com

**Comment by scottsweb** [comment]
Closing due to no response.
