### ISSUE TITLE
Can you turn off updating 

### ISSUE THREAD

**Issue by whwillson** [scottsweb/wp-instagram-widget#70]
Scott- Is it possible to turn off Instagram updating to your WP plugin so the images will remain the same until you turn it back on?

Bill Willson

**Comment by scottsweb** [comment]
Hi Bill

Not really. You could use the cache filter as described in the FAQ to set an extremely long cache time. You could then clear that cache on demand with a transient cleaner: https://en-gb.wordpress.org/plugins/artiss-transient-cleaner/

The code for changing the cache time looks something like this:

```
add_filter('null_instagram_cache_time', 'my_cache_time');

function my_cache_time() {
	return MONTH_IN_SECONDS;
}
```

This would give you one month before the plugin updates.
