### ISSUE TITLE
error 404 ---> link to namesite/instagram.com/namephoto

### ISSUE THREAD

**Issue by Crspost** [scottsweb/wp-instagram-widget#74]
If i click on a photo, the system goes to https://namesite.ext/instagram.com/namephoto 

instead of https://instagram.com/namephoto

thank you for your coding, wp instagram feed is the best IG Plugin on web, really.

my site is SassoMarconiCircoloScacchi.it and the plugin is in a horizontal widget bar near at the end of the page

**Comment by scottsweb** [comment]
This doesn't seem to be an issue with the plugin but an issue with your theme/javascript. The image URLs seem to be highjacked by the fancy loading and transition animations. I would contact your theme author.

**Comment by Crspost** [comment]
my theme is DARINA THEME, it maybe the structure of the theme.

Thank You


2017-11-16 14:58 GMT+01:00 Scott <notifications@github.com>:
