### ISSUE TITLE
Not pulling latest images from instagram

### ISSUE THREAD

**Issue by startedwithasketch** [scottsweb/wp-instagram-widget#75]
Hiya -
the plugin I am using on site www.littlepieceofwonder.co.uk (full width footer) is not pulling through the latest images from Instagram https://www.instagram.com/little.piece.of.wonder/ 

Can you let me know what I can do to fix this?

Thank you

Charlotte

**Comment by scottsweb** [comment]
Hi Charlotte

Images are cached for a few hours and will not be updated instantly on you site. If that is not the problem then please clear your transients with https://wordpress.org/plugins/artiss-transient-cleaner/

More info here: https://wordpress.org/support/topic/the-plugin-has-stopped-to-update-the-photos-2/

**Comment by startedwithasketch** [comment]
That's so helpful and solved the problem - thank you.
