### ISSUE TITLE
wp instagram plugin not getting sync. with my wordpress wesbite

### ISSUE THREAD

**Issue by mosaicpassport** [scottsweb/wp-instagram-widget#78]
I have added  WP Instagram widget on my website, but it is not getting synced with the website as I upload new pictures on Instagram.

Instagram handle : https://www.instagram.com/mosaic_passport/
Webiste: http://mosaicpassport.com/

As you can see the last three pictures are not synced on the website. Let me know if something needs to be done from my end.

**Comment by scottsweb** [comment]
Hi
Can you try the steps outlined here for me: https://github.com/scottsweb/wp-instagram-widget/issues/75

Thanks

**Comment by mosaicpassport** [comment]
It worked. Thank you so much :)
