### ISSUE TITLE
Instagram JSON for HashTag has changed

### ISSUE THREAD

**Issue by MartinPape** [scottsweb/wp-instagram-widget#79]
Hi,

a few days ago Instagram changed the JSON for hashtags you are parsing with your plugin.
This is how it looks now (example):
`...
    "entry_data": {"TagPage": [{"graphql": {"hashtag": {
        "name": "mjsmcffm",
        "is_top_media_only": false,
        "edge_hashtag_to_media": {
            "count": 246,
            "page_info": {
                "has_next_page": true,
                "end_cursor": "J0HWkPm_QAAAF0HWeekigAAAFnIA"
            },
            "edges": [
                {"node": {
                    "comments_disabled": false,
                    "id": "1679227050101297622",
                    "edge_media_to_caption": {"edges": [{"node": {"text": "📸 Reposting @giwtla⠀\n---⠀\nLampenmittwoch - jüdisches Museum Frankfurt #smcffm . #ke17 #mjsmcffm"}}]},
                    "shortcode": "BdN0Brqg9HW",
                    "edge_media_to_comment": {"count": 2},
                    "taken_at_timestamp": 1514399485,
                    "dimensions": {
                        "height": 823,
                        "width": 1080
                    },
                    "display_url": "https://scontent-frt3-1.cdninstagram.com/t51.2885-15/e35/25010057_710846449114068_3412220906716528640_n.jpg",
...`

You should update the parsing code in your plugin and release a new version.

BR - Martin
Thanks for the plugin!

**Comment by scottsweb** [comment]
Thanks for the report. Will work on a fix ASAP
