### ISSUE TITLE
403 URL missing signature date

### ISSUE THREAD

**Issue by rzuf1k** [scottsweb/wp-instagram-widget#81]
Hey, today when I've opened my site with Your plugin every image (out of 6 - in small size) had this 403 error. When I've changed size to large, they appeared again. Switching to other sizes than large didn't help. 
How can I fix this?

Best regards and thanks for awesome plugin!

**Comment by scottsweb** [comment]
I have not seen this error before. Can you tell me if you are using an @username in the widget or a #hashtag and provide a URL if possible. Also can you make sure your Instagram profile is public and that this is indeed the plugin you are using and finally the version you are using.

**Comment by rzuf1k** [comment]
Thanks for reply. Site: http://kamil.sprzedajesz.pl (scroll down to Lions way. @username = @lionsestate (I am not owner of this profile). I am switching back to small images to show error in console.

**Comment by scottsweb** [comment]
I can see the error you are having but I am not sure what is causing it. The profile is public and you should be able to use it. 

Can you let me know what version of this plugin you are using.

**Comment by rzuf1k** [comment]
2.0.1 - installed yesterday. Now i've switched to Large size on Widget options and they are displaying fine.

**Comment by scottsweb** [comment]
I have a hunch this could be Facebook locking down assets to people without a valid API token... I can recreate it locally too. Worrying.

Will see if I can find a fix.

**Comment by scottsweb** [comment]
I have opened a PR above - you can download and test it from here: https://github.com/scottsweb/wp-instagram-widget/tree/81-json-changes (use the green download button)

can you test it for me?!

**Comment by rzuf1k** [comment]
Hey again. I did some tests, it works like a charm now :-) Thank You very much. How did You achieve this? Will obtaining this FB API token protect me from situations like this?

**Comment by scottsweb** [comment]
The JSON embedded into the Instagram site had changed. I used to manipulate the URLs for images sizes but that doesn't seem to work any more. I now use the image sizes they supply.
