### ISSUE TITLE
WP Instagram widget error

### ISSUE THREAD

**Issue by gabrielamarie** [scottsweb/wp-instagram-widget#84]
hey the wp instagram widget is only showing one instagram post on my full width footer.  How can I fix this?

**Comment by scottsweb** [comment]
Hi, I will need more information to help you. 

* What is your website address?
* What is your Instagram username?
* How many images are on your account?
* Is your account public or private?
* Do you see any error messages?
* Have you tried clearing your transients?
* Was it working previously?

**Comment by wwwcardoso** [comment]
hey! the plugin in my site show the error "Unable to communicate with Instagram."

- http://nebrazilbirding.com/about-us/
- @ne_brazil_birding
- plugin default
- public
- Unable to communicate with Instagram.
- yes
- no

**Comment by scottsweb** [comment]
some hosts block outgoing http connections. Try contacting your host to see if this is the case and if they can approve any outgoing requests to the Instagram servers. Sometimes it is possible to do this yourself from within your hosting control panel.
