### ISSUE TITLE
Instagram feed not optimised - slows down site

### ISSUE THREAD

**Issue by chalkandmoss** [scottsweb/wp-instagram-widget#85]
WP-instagram-widget came with the WP theme I bought (Sara by Feb 16th). The instagram feed on chalkandmoss looks great, but site speed tests always show the Instagram images as a red flag, slowing the site down significantly. I had 2 insta feeds showing, and removing one significantly speeded up my site. But I don't want to remove the 2nd one too! How can this be optimised please, so I can have the insta feed with your widget and a fast site? I only upload small, compressed images to my shop and blog, but cannot control  the instagram feed (although there too I mostly upload files around 100k). Could Lazy loading be implemented on the plugin? I have this enabled on my site already though JetPack. The natural image size in the instagram feed are 640x640px, however my images are displayed at max 260px. So should the plugin show the images in a smaller size for speed?
I would really like to continue using your plugin, as the theme was developed with this in mind and it looks great. So I'd love your support on this! Thanks a million.

**Comment by scottsweb** [comment]
Hi
Make sure you select the appropriate image size from the widget settings – you do not need to load a large image into a small area of your theme, this should reduce the scaling.

I would also contact the theme author to see if they can assist you, after all they are selling my plugin and profiting from it.

Finally, when opening a support request it is sensible to supply your website and provide a link to the speed tests you are running.
