### ISSUE TITLE
wp-instagram-widget isn't working

### ISSUE THREAD

**Issue by larmyia** [scottsweb/wp-instagram-widget#92]
Hi. All I'm getting is: Instagram has returned invalid data.

I searched and saw you that it was advised we should update the version. I'm currently using Version 2.0.2 and I can't find anywhere to allow me to update. Please help!

thanks
L-J

**Comment by scottsweb** [comment]
You should be able to update your plugin from WordPress. Tutorial here: https://ithemes.com/2017/02/21/how-to-update-wordpress-plugins/

You can also manually download the latest version from https://wordpress.org/plugins/wp-instagram-widget/
