### ISSUE TITLE
Use JSON endpoints

### ISSUE THREAD

**Issue by scottsweb** [scottsweb/wp-instagram-widget#96]
Avoid the need to parse the HTML and use the JSON feeds instead:

https://www.instagram.com/explore/tags/{tag}/?__a=1

Need to discover the one for a username.

**Comment by preethamvishy** [comment]
The corresponding endpoint for username is:
https://www.instagram.com/<username>/?__a=1

However, Instagram has been denying access to this endpoint at times over the last 2 weeks. Great if it works for you, but I'd as a caveat, I'd ask you to refrain from relying too much on this until all these endpoint changes by Instagram calm down.

**Comment by preethamvishy** [comment]
The corresponding endpoint for username is:
https://www.instagram.com/{username}/?__a=1

However, Instagram has been denying access to this endpoint at times over the last 2 weeks. Great if it works for you, but I'd as a caveat, I'd ask you to refrain from relying too much on this until all these endpoint changes by Instagram calm down.

**Comment by scottsweb** [comment]
Thanks for the info @preethamvishy
