### ISSUE TITLE
Instagram 

### ISSUE THREAD

**Issue by HerbCloutier** [scottsweb/wp-instagram-widget#99]
Good Day,
I added the WPinstagram to a weaver II theme template for a client and when I activate the widget it says Unable to communicate with Instagram? I haven't been able to find a solution to this. Can you please give some direction on how to proceed?
Thank you
Herb Cloutier

**Comment by scottsweb** [comment]
This is normally caused by a host that blocks outgoing connections. I would contact your host first to see if that is the case.
